"""
Pydantic models used throughout the app.

Two categories:
1. Models the LLM is FORCED to conform to via Gemini's structured output
   (response_schema). This is the primary anti-hallucination guardrail --
   Gemini cannot return free-form prose, only JSON matching this shape.
2. Models computed deterministically in Python from the LLM's structured
   output (e.g. BudgetFeasibility) -- arithmetic is NEVER delegated to the
   model.
"""

from __future__ import annotations

from typing import List, Optional
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Input models (validated before anything is sent to Gemini)
# ---------------------------------------------------------------------------

class UserInput(BaseModel):
    budget_limit: float = Field(gt=0, description="Total budget for the day's groceries")
    currency: str = Field(default="INR", description="Currency code, e.g. INR, USD, EUR")
    dietary_preference: str = Field(description="e.g. Vegetarian, Vegan, Non-Vegetarian, Eggetarian, No restriction")
    allergies_or_dislikes: List[str] = Field(default_factory=list)
    cuisine_preference: Optional[str] = Field(default=None, description="e.g. Indian, Italian, Mexican")
    day_type: str = Field(description="e.g. 'Busy day - quick meals', 'Normal day', 'Free day - elaborate cooking'")
    pantry_items: List[str] = Field(default_factory=list, description="Ingredients already available at home")


# ---------------------------------------------------------------------------
# LLM-generated models (schema enforced via Gemini response_schema)
# ---------------------------------------------------------------------------

class Meal(BaseModel):
    name: str = Field(description="Name of the dish")
    description: str = Field(description="1-2 sentence description of the dish and how it fits the day type")
    prep_time_minutes: int = Field(description="Estimated total prep + cook time in minutes")
    calories_estimate: Optional[int] = Field(default=None, description="Rough calorie estimate per serving")


class MealPlan(BaseModel):
    breakfast: Meal
    lunch: Meal
    dinner: Meal


class GroceryItem(BaseModel):
    name: str
    quantity: str = Field(description="Quantity needed, e.g. '2 cups', '500 g', '3 pieces'")
    category: str = Field(description="e.g. Produce, Dairy, Grains, Protein, Spices, Other")
    estimated_unit_price: float = Field(
        ge=0, description="Estimated cost for this quantity, in the user's stated currency"
    )
    used_in: List[str] = Field(description="Which meals use this item, e.g. ['breakfast', 'dinner']")
    already_in_pantry: bool = Field(
        default=False, description="True if the user already has this item and doesn't need to buy it"
    )


class Substitution(BaseModel):
    original_item: str
    substitute_options: List[str] = Field(description="2-3 realistic substitute ingredients/dishes")
    reason: str = Field(description="Why this substitution works: cheaper, allergy-safe, more available, etc.")


class MealPlanLLMResponse(BaseModel):
    """The exact JSON shape Gemini is constrained to return."""
    meal_plan: MealPlan
    grocery_list: List[GroceryItem]
    substitutions: List[Substitution]
    notes: Optional[str] = Field(default=None, description="Any caveats worth surfacing to the user")


# ---------------------------------------------------------------------------
# Deterministic, Python-computed models (never generated by the LLM)
# ---------------------------------------------------------------------------

class BudgetFeasibility(BaseModel):
    total_estimated_cost: float
    budget_limit: float
    currency: str
    is_within_budget: bool
    difference: float
    message: str
    cost_saving_tips: List[str] = Field(default_factory=list)


class FullPlanResponse(BaseModel):
    llm_response: MealPlanLLMResponse
    budget: BudgetFeasibility
